INSTALL_TARGET_PROCESSES = SpringBoard

ARCHS = arm64 arm64e armv7

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = showbattery

showbattery_FILES = Tweak.xm
showbattery_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
